Update to allow for Capital Y/N when confirming

diff --git a/push b/push
--- a/push
+++ b/push
@@ -36,18 +36,18 @@ git status --short
 # Ask for confirmation before pushing changes
 echo "Are you sure you want to push changes to $current_branch on GitHub? (y/n)"
 read confirm
-if [ "$confirm" != "y" ]; then
+if [[ "$confirm" =~ ^[Yy]$ ]]; then
+  # Commit changes to Git and push to GitHub
+  echo "Committing changes and pushing to $current_branch on GitHub..."
+  if ! git commit -m "$commit_message" &> /dev/null || ! git push origin "$current_branch" &> /dev/null; then
+    echo "Error: Commit and push failed. Git messages:"
+    git commit -m "$commit_message"
+    git push origin "$current_branch"
+    exit 1
+  else
+    echo "Changes have been committed and pushed to $current_branch on GitHub."
+  fi
+else
   echo "Aborted."
   exit 0
-fi
-
-# Commit changes to Git and push to GitHub
-echo "Committing changes and pushing to $current_branch on GitHub..."
-if ! git commit -m "$commit_message" &> /dev/null || ! git push origin "$current_branch" &> /dev/null; then
-  echo "Error: Commit and push failed. Git messages:"
-  git commit -m "$commit_message"
-  git push origin "$current_branch"
-  exit 1
-else
-  echo "Changes have been committed and pushed to $current_branch on GitHub."
 fi
diff --git a/pushall b/pushall
--- a/pushall
+++ b/pushall
@@ -23,7 +23,12 @@ git status --short
 # Ask for confirmation before pushing changes
 echo "Are you sure you want to push changes to $current_branch on GitHub? (y/n)"
 read confirm
-if [ "$confirm" != "y" ]; then
+confirm=$(echo "$confirm" | tr '[:upper:]' '[:lower:]') # convert to lowercase
+if [[ "$confirm" != "y" && "$confirm" != "n" ]]; then
+  echo "Invalid input. Aborted."
+  exit 1
+fi
+if [[ "$confirm" = "n" ]]; then
   echo "Aborted."
   exit 0
 fi
